"""The migrations, checked by the machine instead of by whoever last read the revision.

`Base.metadata` and the revision in `migrations/versions/` are two descriptions of one schema,
written by hand at different times, and nothing in the fast suite compares them. Fase 4 compared
them once, by running `alembic check` against a database by hand and reading the answer. A check
that has to be remembered is a check that stops happening, so it lives here now.

The container these run against was migrated by the fixture, with the same `env.py` and the same
revision scripts production uses, which is what makes the comparison mean anything: a schema built
from `Base.metadata.create_all()` would agree with the models by construction and would tell
nobody whether the migration works.
"""

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import Engine, text

from tests.integration.conftest import alembic_config

pytestmark = pytest.mark.integration


def test_the_migrated_schema_is_exactly_what_the_models_declare(database_dsn: str) -> None:
    """
    Given a database with the migrations applied,
    when it is compared against `Base.metadata`,
    then Alembic finds nothing to add, drop or alter.

    `command.check` raises `AutogenerateDiffsDetected` listing the differences when there are any,
    so calling it *is* the assertion -- and a better one than any hand-written comparison, because
    it is the same comparison `--autogenerate` uses to write migrations in the first place.

    What this catches is the mistake that survives every other test in this suite: a column added
    to an entity and never migrated. The application would keep passing until the first insert
    against a database nobody had rebuilt.
    """
    command.check(alembic_config(database_dsn))


def test_the_container_is_at_the_head_this_repository_declares(
    database_dsn: str, database: Engine
) -> None:
    """
    Given the revision the fixture applied,
    when it is compared with the head of `migrations/versions/`,
    then they are the same.

    The guard on the fixture rather than on the schema. `alembic upgrade head` failing silently, or
    a second revision arriving without the fixture being re-run, would leave the whole suite
    testing a schema nobody declared -- and the test above would not notice, because it compares
    the database against the models and not against the revision history.
    """
    head = ScriptDirectory.from_config(alembic_config(database_dsn)).get_current_head()

    with database.connect() as connection:
        applied = connection.execute(text("SELECT version_num FROM alembic_version")).scalar_one()

    assert head is not None
    assert applied == head


def test_the_click_index_the_count_relies_on_really_exists(database: Engine) -> None:
    """
    Given the schema the migrations produced,
    when the indexes on `click` are read out of the catalogue,
    then `ix_click_link_id` is among them.

    `total_clicks` is a `COUNT` over one link's rows, and the whole reason that is an acceptable
    price on the read path is this index. Without it the count is a sequential scan of every click
    ever recorded, and nothing in any response would say so -- the number would still be right, and
    would get slower every day.
    """
    with database.connect() as connection:
        indexes = set(
            connection.execute(
                text("SELECT indexname FROM pg_indexes WHERE tablename = 'click'")
            ).scalars()
        )

    assert "ix_click_link_id" in indexes
